services:
  - type: web
    name: techzone-portal
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_CONFIG
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: DEBUG
        value: false
